### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by Gabbyr** [Verigreen/verigreen#132]
we are getting this error when hook is running by a push:

remote: Exception in thread "main" java.lang.IllegalArgumentException
remote:         at org.springframework.asm.ClassReader.<init>(Unknown Source)
remote:         at org.springframework.asm.ClassReader.<init>(Unknown Source)
remote:         at org.springframework.asm.ClassReader.<init>(Unknown Source)
remote:         at org.springframework.core.LocalVariableTableParameterNameDiscoverer.inspectClass(LocalVariableTableParameterNameDiscoverer.java:110)
remote:         at org.springframework.core.LocalVariableTableParameterNameDiscoverer.getParameterNames(LocalVariableTableParameterNameDiscoverer.java:85)
remote:         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:193)
remote:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1051)
remote:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:955)
remote:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:490)

what is missing here ?

Thanks,

Gabby

**Comment by aleitamar** [comment]
Make sure you are running the hook with java 7

**Comment by gromano-dev** [comment]
It runs with java 1.7 . What else could it be ?

On Mar 10, 2018 06:35, "aleitamar" <notifications@github.com> wrote:

Make sure you are running the hook with java 7

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Verigreen/verigreen/issues/132#issuecomment-372002028>,
or mute the thread

**Comment by gromano-dev** [comment]
solved it with full path to java. JAVA_HOME was not enough for this.
i have an HTTP client issue now but I don't see why since the base jenkins URL is ok in the config file. jenkins is up and running of course. what  am I missing here ?

remote: Exception in thread "main" java.lang.RuntimeException: com.verigreen.restclient.common.RestClientException: Failed : HTTP error code : 404 response message: <html><head><title>Apache Tomcat/7.0.84 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /rest/verigreen-needed</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/rest/verigreen-needed</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.84</h3></body></html>

**Comment by soninob** [comment]
@Gabbyr - can you please post your config file?

**Comment by gromano-dev** [comment]
Barak - do you see anything unusual there ?

Gabby

**Comment by soninob** [comment]
@Gabbyr - I would like to see the config file, it seems like something is missing.
Do you have pointer to the /rest on the path?
Also, please verify that the collector is up and running, do you see th UI?

**Comment by gromano-dev** [comment]
what pointer ? which path ?

I see the error on the client side like this :

otal 4 (delta 3), reused 0 (delta 0)
remote: Exception in thread "main" java.lang.RuntimeException:
com.verigreen.restclient.common.RestClientException: Failed : HTTP error
code : 404 response message: <html><head><title>Apache Tomcat/7.0.84 -
Error report</title><style></style>
</head><body><h1>HTTP Status 404 - /rest/verigreen-needed</h1><HR size="1"
noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>
*/rest/verigreen-needed*</u></p><p><b>description</b> <u>The requested
resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache
Tomcat/7.0.84</h3></body></html>
remote:         at
com.verigreen.hook.BranchOperator.checkIfVerigreenNeeded(BranchOperator.java:113)
remote:         at
com.verigreen.hook.BranchOperator.processBranch(BranchOperator.java:56)
remote:         at com.verigreen.hook.EntryPoint.main(EntryPoint.java:38)

What is verigreen needed means ?


Gabby

**Comment by soninob** [comment]
Gabby - please check this file on the hook machine [hook.properties](https://github.com/Verigreen/verigreen/blob/master/git-hook/resources/hook.properties).
Make sure that you have the right IP address for the collector.
Also, make sure that the hook machine (the bit bucket machine) can ping the collector machine.
Let me know if we can close this issue/

**Comment by gromano-dev** [comment]
thanks - will check later today. I will call you regarding the Jenkins 2.X
support and maybe we will pull this up.

Gabby

**Comment by soninob** [comment]
@Gabbyr - any news with the hook? is it working now?

**Comment by soninob** [comment]
Closing for now, @Gabbyr if it is still relevant, please reopen
