### ISSUE TITLE
Dummy proof idiot's guide to setup verigreen? 

### ISSUE THREAD

**Issue by siministry** [Verigreen/verigreen#16]
Is there a dummy proof idiot's guide to setup verigreen? 
I certainly wish that the deployment wiki can be easy 1-2-3 for no-tech folks like me.
I tried both docker verigreen/vg-collector image and building from scratch but no luck at all...

Would love to see an idiot's guide that covers complete hooking up of github/jenkins/verigreen with examples.

Many thanks!

**Comment by eitansch** [comment]
Thanks for the comment.
We're actually actively working on exactly that - one-click setup of Vergireen (complete with Jenkins and Stash/Gitlab) for POC and initial ramp-up.
Once it's available we'll publish it and you'll be able to d/l it and use it.

Having said that - feel free to reach out to us with specific questions and queries on setup and I'm sure we'll be able to help you to quickly run Verigreen.

Cheers.

**Comment by rqc** [comment]
@ahxiangg Since you mentioned Github, I would like to add that we do not support Github repositories yet since there are some limitations to how Github webhooks work in order for Verigreen to serve as a pre-receive gate-checker. We are still researching that and hopefully will provide support in the near future. As @eitanshp mentioned, we have full support for Stash and currently have plans to start our support for Gitlab.

If you would like, you may provide any errors that you're receiving when following the instructions here: https://registry.hub.docker.com/u/verigreen/vg-collector/ and we will be happy to guide you.

Thanks for your feedback!

**Comment by siministry** [comment]
@rqc Thanks for sharing the limitations on Verigreen with GitHub. This is interesting, Can you share more on the webhooks limitations on GH compared to Stash?

**Comment by rqc** [comment]
@ahxiangg Github's webhooks are triggered from events _a posteriori_, i.e. **after** something occurs in the repo, Github triggers an action via an HTTP request to an endpoint of your choice. The issue with this when it comes to Verigreen, is that it does not allow us to _catch_ push events on a Github repository before they are applied. Instead, we would need Github to trigger an action **before** the event occurs. This is what is called a _pre-receive_ hook. Stash provides this functionality by using either regular git hooks or using the _Pre-receive Hook Plugin_. Until Github provides such functionality or we can implement a solution around this we are just supporting Verigreen with Stash (and GitLab in the near future).

Thanks for your interest in using Verigreen. Please feel free to contact us.
